import { useState, useCallback } from "react";
import { DocumentSidebar } from "@/components/DocumentSidebar";
import { ChatInterface } from "@/components/ChatInterface";
import { UploadModal } from "@/components/UploadModal";
import { Document, Message } from "@/types/document";
import { useToast } from "@/hooks/use-toast";

// Mock data for demo
const mockDocuments: Document[] = [
  {
    id: "1",
    name: "Financial Report Q4 2024.pdf",
    type: "pdf",
    size: 2456000,
    uploadedAt: new Date("2024-12-15"),
    pageCount: 48,
  },
  {
    id: "2",
    name: "Technical Specification v2.1.docx",
    type: "docx",
    size: 1234000,
    uploadedAt: new Date("2024-12-18"),
    pageCount: 156,
  },
  {
    id: "3",
    name: "Research Paper - Machine Learning.pdf",
    type: "pdf",
    size: 5678000,
    uploadedAt: new Date("2024-12-20"),
    pageCount: 324,
  },
];

const Index = () => {
  const [documents, setDocuments] = useState<Document[]>(mockDocuments);
  const [selectedDocument, setSelectedDocument] = useState<Document | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [uploadModalOpen, setUploadModalOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleSelectDocument = useCallback((doc: Document) => {
    setSelectedDocument(doc);
    setMessages([]); // Reset messages when switching documents
  }, []);

  const handleUpload = useCallback(
    (files: File[]) => {
      const newDocs: Document[] = files.map((file, index) => ({
        id: `new-${Date.now()}-${index}`,
        name: file.name,
        type: file.name.endsWith(".pdf") ? "pdf" : "docx",
        size: file.size,
        uploadedAt: new Date(),
        pageCount: Math.floor(Math.random() * 200) + 50,
      }));

      setDocuments((prev) => [...newDocs, ...prev]);
      toast({
        title: "Documents uploaded",
        description: `${files.length} document${files.length > 1 ? "s" : ""} indexed successfully`,
      });
    },
    [toast]
  );

  const handleDeleteDocument = useCallback(
    (id: string) => {
      setDocuments((prev) => prev.filter((doc) => doc.id !== id));
      if (selectedDocument?.id === id) {
        setSelectedDocument(null);
        setMessages([]);
      }
      toast({
        title: "Document deleted",
        description: "The document has been removed from the index",
      });
    },
    [selectedDocument, toast]
  );

  const handleSendMessage = useCallback((content: string) => {
    // Add user message
    const userMessage: Message = {
      id: `msg-${Date.now()}`,
      role: "user",
      content,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, userMessage]);
    setIsLoading(true);

    // Simulate AI response
    setTimeout(() => {
      const aiMessage: Message = {
        id: `msg-${Date.now()}-ai`,
        role: "assistant",
        content: `Based on the document, here's what I found regarding your question about "${content}":\n\nThis is a simulated response. In a real implementation, this would be the answer generated by your RAG pipeline and LLM, pulling relevant information from the vector database and generating a comprehensive response.\n\nThe response would include citations and references to specific sections of the document.`,
        timestamp: new Date(),
        sources: [
          { page: 12, excerpt: "Relevant section from page 12..." },
          { page: 45, excerpt: "Supporting information from page 45..." },
        ],
      };
      setMessages((prev) => [...prev, aiMessage]);
      setIsLoading(false);
    }, 2000);
  }, []);

  return (
    <div className="flex h-screen w-full overflow-hidden bg-gradient-to-br from-background via-background to-accent/20">
      {/* Sidebar */}
      <DocumentSidebar
        documents={documents}
        selectedDocument={selectedDocument}
        onSelectDocument={handleSelectDocument}
        onUploadClick={() => setUploadModalOpen(true)}
        onDeleteDocument={handleDeleteDocument}
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
      />

      {/* Main Chat Area */}
      <ChatInterface
        document={selectedDocument}
        messages={messages}
        onSendMessage={handleSendMessage}
        isLoading={isLoading}
      />

      {/* Upload Modal */}
      <UploadModal
        open={uploadModalOpen}
        onOpenChange={setUploadModalOpen}
        onUpload={handleUpload}
      />
    </div>
  );
};

export default Index;
